# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://www.iroak.art/"
title: Echo
paginate: 5
theme: [hugo-PaperMod]
languageCode: zh-cn

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

# 选择languages字段的哪个语言，默认 en
defaultContentLanguage: zh
languages:
  zh:
    permalinks:
      # 默认路径会带 /posts 前缀
      posts: /:slug
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: 文章
          url: archives
          weight: 1
        - name: 系列
          url: series
          weight: 2
        - name: search
          url: search
          weight: 3
        # - name: WiKi
        #   url: https://github.com/adityatelange/hugo-PaperMod/wiki/

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  homeInfoParams:
    Title: "Hi! I'm iroak"
    Content: "一个不善言语的普通人，希望在这一隅，留下些许痕迹。"
  socialIcons:
    - name: github
      title: Github
      url: "https://github.com/mio-1"
    - name: x
      title: XD
      url: "https://x.com/Trial_Sword"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://ko-fi.com/iroak_"
  editPost:
    URL: "https://github.com/mio-1/echo/tree/master/content"
    Text: "指出问题"
    appendFilePath: true # to append file path to Edit link
  description: "静处"
  # author: ["Me", "You"] # multiple authors
  author: iroak
  defaultTheme: auto
  # 支持分享的平台 X / facebook / reddit / telegram / whatsapp / ycombinator / linkedin
  ShowShareButtons: true
  ShareButtons:
  - x
  - telegram
  - email
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  tocopen: false
  # comments: false
  # images: ["images/papermod-cover.png"]
  DateFormat: "2006-01-02"
  profileMode:
    enabled: false
    title: profile
    imageUrl: "#"
    imageTitle: my image
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    # disableHLJS: true
    favicon: "/resources/icon/favicon.ico"
    favicon16x16: "/resources/icon/favicon-16x16.png"
    favicon32x32: "/resources/icon/favicon-32x32.png"
    apple_touch_icon: "/resources/icon/apple-touch-icon.png"
    safari_pinned_tab: "/resource/icon/safari_pinned_tab.png"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
